# install neccessary packages
- name: Ensure neccessary packages are installed.
  ansible.builtin.apt:
    pkg:
    - fzf
    - zsh
    - zsh-syntax-highlighting
    - stow
    - openjdk-11-jdk-headless
    - graphviz
    - npm
    state: present

- name: Ensure vs-code is installed.
  community.general.snap:
    name: code
    classic: true

# install node version manager  if not already done
- name: Ensure NVM is installed.
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
  args:
    creates: "/home/{{ vm_user }}/.nvm/nvm.sh"

# clone gitlab repo if not already
- name: Ensure ProfitEngineers GitLab repository is cloned.
  ansible.builtin.git:
    repo: "https://{{ gitlab_user }}:{{ gitlab_token }}@git.it.hs-heilbronn.de/it/courses/seb/pmt/pmt-sose-23/profitengineers.git"
    dest: "/home/{{ vm_user }}/profitengineers"
    version: main
    accept_hostkey: yes

- name: Ensure Dotfiles repository is cloned.
  ansible.builtin.git:
    repo: "https://{{ gitlab_user }}:{{ gitlab_token }}@git.it.hs-heilbronn.de/ckiriakou/labswp-dotfiles.git"
    dest: "/home/{{ vm_user }}/.dotfiles"
    version: main
    accept_hostkey: yes

# Set email address in git config
- name: Ensure E-Mail git config entry is set.
  community.general.git_config:
    name: user.email
    repo: '/home/{{ vm_user }}/profitengineers'
    scope: local
    value: '{{ gitlab_user }}@stud.hs-heilbronn.de'

# Set full name in git config
- name: Ensure Name git config entry is set.
  community.general.git_config:
    name: user.name
    repo: '/home/{{ vm_user }}/profitengineers'
    scope: local
    value: '{{ forename }} {{ surname }}'

# Install typescript via npm
- name: Ensure Typescript NPM package is installed.
  community.general.npm:
    name: typescript
    global: yes

# Install angular via npm
- name: Ensure Angular CLI NPM package is installed.
  community.general.npm:
    name: '@angular/cli'
    global: no
    path: "/home/{{ vm_user }}/profitengineers"

# Change ownership of files
- name: Change ownership to the normal user including hidden files and excluding a directory
  ansible.builtin.shell: >
    "find /home/{{ vm_user }} -type f -o -type d ! -path '/home/{{ vm_user }}/snap' -exec chown {{ vm_user }}:{{ vm_user }} {} +"

